# -*- coding: utf-8 -*-
"""reto8 (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DMB-jem_vCLvVbKW_HHLclANgIoD7l0T

De los retos anteriores selecione 3 funciones y escribalas en forma de lambdas.
"""

#Imprimir un listado con los números del 1 al 100 cada uno con su respectivo cuadrado.
if __name__ == "__main__":
  n_cuadrado = lambda n: n**2 # se define la funcion lambda
  for n in range(1, 101): # se establece el rango
    print(n, n_cuadrado(n)) # se llama a esta funcion lambda

#Imprimir un listado con los números impares desde 1 hasta 999 y seguidamente otro listado con los números pares desde 2 hasta 1000.
if __name__ == "__main__":
    imprimir = lambda numeros: [print(n) for n in numeros]  # Lambda que imprime cada número en la lista
    impares = list(range(1, 1000, 2))  # es el rango que recorren los impares de 1 a 999
    pares = list(range(2, 1001, 2)) # es el rango que recorren los pares de 2 a 100
    print("Numeros impares:")
    imprimir(impares)  # se llama a la función lambda con los impares
    print("Numeros pares:")
    imprimir(pares)  # se llama a la función lambda con los pares

#Implementar un programa que ingrese un número de 2 a 50 y muestre sus divisores.
if __name__ == "__main__":
    numero = int(input("pon un numero entre 2 y 50: ")) # el ususario ingresara el numero
    if 2 <= numero <= 50: # se valida que el numero este dentro del rango establecido
        divisores = lambda n: [x for x in range(1, n + 1) if n % x == 0]  # Función lambda para obtener divisores
        print("divisores de " + str(numero), ":" + str(divisores(numero))) # nos entrega el divisor
    else:
        print("numero no valido. Debe estar entre 2 y 50.")

"""De los retos anteriores selecione 3 funciones y escribalas con argumentos no definidos (*args)."""

# Encontrar el factorial de un número
def factorial(*args): # definimos la funcion
        fact = 1
        for i in range(1, num + 1): # se establece el rango el cual sera dado desde uno hasta el numero que vayamos a seleccionar
            fact *= i # expresamos la operacion de el numero con forme este avance en el recorrido de su rango (factorial jeje)
        return fact # nos retorna el resultado
if __name__ == "__main__":
  num = int(input("ingrese el numero: ")) # ingresamos el numero al cual le calcularemos factorial
  print("El factorial de " + str(num) + " es " + str(factorial(num)))

# Diseñe una función que calcule la cantidad de carne de aves en kilos si se tienen N gallinas, M gallos y K pollitos cada uno pesando 6 kilos, 7 kilos y 1 kilo respectivamente.
def cantidad_carne(*args):
    N, M, K = args  # desempaquetamos el argumento
    # Pesos de cada tipo de animal en kilos
    peso_gallina = 6
    peso_gallo = 7
    peso_pollito = 1
    total_carne = (N * peso_gallina) + (M * peso_gallo) + (K * peso_pollito) # calculamos la suma de los pesos de cada tipo de animal multiplicando su peso por el numero de animales que hay de cada tipo
    return total_carne # nos retorna el resultado
if __name__ == "__main__":
  n = int(input("Ingrese el número de gallinas: ")) # ingresamos el numero de gallinas
  m = int(input("Ingrese el número de gallos: ")) # ingresamos el numero de gallos
  k = int(input("Ingrese el número de pollitos: ")) # ingresamos el numero de pollitos
  total_carne = cantidad_carne(n, m, k)# Llamamos a la funcion
  print(f"El peso total de los animales es: {total_carne} kilos")   # Imprimimos el resultado de la funcion anterior

# Haga un programa que utilice una función para calcular el valor de un préstamo C usando interés compuesto del i por n meses.
def calcular_prestamo(*args):
    P, i, n = args  # Desempaquetamos el argumento
    C = P * (1 + (i / 100))**n # Calculamos el valor final del préstamo usando la fórmula de interés compuesto
    return C # nos retorna un resultado
if __name__ == "__main__":
    p = float(input("Ingrese el valor inicial del prestamo: ")) # ingresas el valor inicial
    i = float(input("Ingrese la tasa de interes mensual: ")) # ingresamos la tasa de interes mensual
    n = int(input("Ingrese el numero de meses: ")) # ingresas el numero de meses
    valor_final = calcular_prestamo(p, i, n) # Llamamos a la funcion
    print("El valor final del prestamo es: " + str(valor_final)) # imprimimos el resultado de la funcion anterior

"""Escriba una función recursiva para calcular la operación de la potencia."""

def pot_recursiva(base, n):
    if n < 0:
        return 1 / pot_recursiva(base, -n) # exponentes negativos
    if n == 0:
        return 1 #exponente igual a 0 el resultado es 1
    return base * pot_recursiva(base, n - 1) # establecemos la condicion recursiva

if __name__ == "__main__":
        base = int(input("Ingrese la base: ")) # se hace el input de la base que sera elevada
        n = int(input("Ingrese el exponente: ")) # la potencia a la cual se eleva la base
        resultado = pot_recursiva(base, n)
        print(str(base) + " elevado a " + str(n) + " es: " + str(resultado)) # se hace la impresion del resultado de manera detallada

"""Realice pruebas para calcular fibonacci con iteración o con recursión. Determine desde que número de la serie la diferencia de tiempo se vuelve significativa."""

import time

def fibonacci_recursivo(n):
    if n <= 1:
        return n
    return fibonacci_recursivo(n-1) + fibonacci_recursivo(n-2)

def fibonacci_iterativo(n):
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    return a

diferencia_significativa = None

for n in range(30, 41):  # reducimos el rango
    # Medimos el tiempo recursivo
    start_time = time.time()
    fibonacci_recursivo(n)
    end_time = time.time()
    timer_recursivo = end_time - start_time

    # Medimos el tiempo iterativo
    start_time = time.time()
    fibonacci_iterativo(n)
    end_time = time.time()
    timer_iterativo = end_time - start_time

    diferencia = timer_recursivo - timer_iterativo
    print("n = " + str(n) + " Recursivo: " + str(timer_recursivo) + " seg, Iterativo: " + str(timer_iterativo) + " seg, Diferencia: " + str(diferencia) + " seg")

    if not diferencia_significativa and diferencia > 0:
      diferencia_significativa = n

if diferencia_significativa:
    print("La diferencia de tiempo se vuelve significativa a partir de " + str(diferencia_significativa))
else:
    print("No se encontró una diferencia significativa.")